### ISSUE TITLE
CoM not working

### ISSUE THREAD

**Issue by linuxgurugamer** [DefiantZombie/FlightMarkers#7] opened 2020-01-04 19:27 UTC
The CoM marker is not being recalculated as fuel is burned.  
Try launching KerbalX ( the rocket) and turn them on.  It only changes when parts are staged

**Comment by DefiantZombie** [comment] 2020-02-12 22:08
Center of Mass marker is not being calculated by the mod. It is read directly from the vessel in KSP.

I am unable to attempt to replicate without knowing which KSP and mod version the bug is being reported for.

(I swear I wasn't ignoring you, Github appears to be refusing to send me notifications again)

**Comment by linuxgurugamer** [comment] 2020-03-02 19:43
and I'm not ignoring you, either :-)
It would have been 1.8.1, and the current version of the mod

**Comment by DefiantZombie** [comment] 2020-07-02 04:44
Unable to reproduce during my KSP 1.10.0 update checks. Closing issue.

**Closed as completed by DefiantZombie** 2020-07-02 04:44 UTC
Labels: Type: Bug
